spring:
  application:
    name: ai-service


  data:
    mongodb:
      uri: mongodb://localhost:27017/airecommendation
      database: airecommendation

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}

kafka:
  topic:
    name: activity-events




server:
  port: 8083