name: Build Fitness Microservices

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build User Service
        run: mvn -B package -DskipTests
        working-directory: FitnessApplication/fitnessBackend/userservice

      - name: Build Activity Service
        run: mvn -B package -DskipTests
        working-directory: FitnessApplication/fitnessBackend/activityservice

      - name: Build AI Service
        run: mvn -B package -DskipTests
        working-directory: FitnessApplication/fitnessBackend/aiservice

      - name: Build Gateway Service
        run: mvn -B package -DskipTests
        working-directory: FitnessApplication/fitnessBackend/gatewayservice

      - name: Build Eureka Server
        run: mvn -B package -DskipTests
        working-directory: FitnessApplication/fitnessBackend/eureka

      - name: Build Config Server
        run: mvn -B package -DskipTests
        working-directory: FitnessApplication/fitnessBackend/configserver
